# Generated by Django 5.2.16 on 2026-07-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
