# Generated by Django 5.2.16 on 2026-07-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parent_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
