# Generated by Django 5.2.16 on 2026-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_parent_resume_resume_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
