# Generated by Django 5.2.16 on 2026-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resume_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
